[package]
name = "tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
dirs = "5.0.1"
edit = "0.1.5"
rusqlite = "0.32.1"
serde = "1.0.217"
serde_derive = "1.0.217"
tempfile = "3.14.0"
toml = "0.8.19"
